### ISSUE TITLE
Android - Freshchat fails to register push token

### ISSUE THREAD

**Issue by OyaSaid** [freshworks/freshchat-android#111] opened 2020-11-04 12:57 UTC
The use case is very simple:
- User logs in
- Freshchat : init(FreshchatConfig) is called
- Freshchat : setPushRegistrationToken(token) is called

The problem is that **sometimes** after login, the push notifications are not being received. This behaviour is not consistent (sometimes push notifications are received, sometimes they aren't). It seems to be a concurrency issue, because if a delay is put on the push token registration, then everything seems to work fine.

Is there a way to fix this without that delay? 
Is there a way to have a listener to know when the initialization has finished?
Why is the init method and the setting of the push registration token method dependant?

This issue occurs on v 4.0.0

**Comment by MuthuFD** [comment] 2020-11-07 03:20
@OyaSaid 
You are right. Init and setPushRegistrationToken are not related.

We tried few times reproducing this by calling init on a button click and setPushRegistrationToken is called ahead of init.

But we are not able to reproduce.

Can you use the sample app in this repo to reproduce this issue and share it with us?

**Comment by zoey-juan** [comment] 2020-11-09 11:09
Hi @MuthuFD,
the issue is
1. first calling init
2. setPushRegistrationToken called `AFTER` init

if setPushRegistrationToken before init, it works fine.
Due to some reason, `setPushRegistrationToken` will be called after init in our case.
However, setPushRegistrationToken should be called any time when token changed and independent with init.

**Comment by rameshfreshworks** [comment] 2020-12-07 08:49
This issue has been fixed in version 4.1.1.

**Closed by rameshfreshworks** 2020-12-07 08:49 UTC
