### ISSUE TITLE
Crash : com.freshchat.consumer.sdk.d.b.create

### ISSUE THREAD

**Issue by supercellZ-swvl** [freshworks/freshchat-android#129] opened 2021-03-11 13:37 UTC
## Describe the bug
Showing up on my Crashlytics :

## Steps to reproduce
```    
* Unfortunately I don't have a way to reproduce it.
```

## Expected behavior
Expected the app not to crash.

## Platform
- [ ] Android

## Freshchat SDK version
- SDK version : 4.1.0

## Device information
Galaxy Note 3

```
Provide device details here like
 * Device name : Galaxy Note 3
 * OS version : Android 5.0
 * State : Always happens in the Background 100%

```

## Crash log
if applicable, add logs here to help us debug the problem
`Fatal Exception: java.lang.AssertionError: impossible
       at java.lang.Enum$1.create(Enum.java:45)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Class.getEnumConstants(Class.java:1072)
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:795)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.Gson.fromJson(Gson.java:886)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at com.google.gson.Gson.fromJson(Gson.java:773)
       at com.freshchat.consumer.sdk.j.ab.fromJson(ab.java)
       at com.freshchat.consumer.sdk.j.bc.bH(bc.java)
       at com.freshchat.consumer.sdk.j.ap.bE(ap.java)
       at com.freshchat.consumer.sdk.j.ap.bD(ap.java)
       at com.freshchat.consumer.sdk.j.w.bx(w.java)
       at com.freshchat.consumer.sdk.j.w.ay(w.java)
       at com.freshchat.consumer.sdk.service.c.v.a(v.java)
       at com.freshchat.consumer.sdk.service.c.v.b(v.java)
       at com.freshchat.consumer.sdk.service.c.v.b(v.java)
       at com.freshchat.consumer.sdk.service.b.b.b(b.java)
       at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(FreshchatService.java)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)`
       
       Caused by :
       `Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getDeclaredMethod(Class.java:635)
       at java.lang.Enum$1.create(Enum.java:41)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Class.getEnumConstants(Class.java:1072)
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:795)
       at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:506)
       at com.freshchat.consumer.sdk.d.b.create(b.java)
       at com.google.gson.Gson.getAdapter(Gson.java:423)
       at com.google.gson.Gson.fromJson(Gson.java:886)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at com.google.gson.Gson.fromJson(Gson.java:773)
       at com.freshchat.consumer.sdk.j.ab.fromJson(ab.java)
       at com.freshchat.consumer.sdk.j.bc.bH(bc.java)
       at com.freshchat.consumer.sdk.j.ap.bE(ap.java)
       at com.freshchat.consumer.sdk.j.ap.bD(ap.java)
       at com.freshchat.consumer.sdk.j.w.bx(w.java)
       at com.freshchat.consumer.sdk.j.w.ay(w.java)
       at com.freshchat.consumer.sdk.service.c.v.a(v.java)
       at com.freshchat.consumer.sdk.service.c.v.b(v.java)
       at com.freshchat.consumer.sdk.service.c.v.b(v.java)
       at com.freshchat.consumer.sdk.service.b.b.b(b.java)
       at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(FreshchatService.java)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

## Screenshot/ Video recording 
If applicable, add screenshots/video recording to help explain your problem.

**Comment by rameshfreshworks** [comment] 2021-05-13 11:04
We are unable to reproduce this issue on our side as well. We are closing this for now. 
if you still need assistance on this issue, reach out to us through support@freshchat.com.

**Closed by rameshfreshworks** 2021-05-13 11:04 UTC
