### ISSUE TITLE
freshchatNotification is always 0

### ISSUE THREAD

**Issue by Shekhar7860** [freshworks/freshchat-android#102] opened 2020-08-18 10:21 UTC
when i console or alert freshchatNotification , it always gives 0

**Comment by Shekhar7860** [comment] 2020-08-18 13:08
when i log - freshchatNotification it gives 0, what it means???

**Comment by MuthuFD** [comment] 2020-08-19 04:04
Duplicate of https://github.com/freshworks/freshchat-android/issues/101

**Closed** 2020-08-19 04:56 UTC
